modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="coordinatesdisplay" #mandatory
version="2.0.0" #mandatory
displayName="Coordinates Display" #mandatory
authors="Boxadactle" #optional
description='''
A coordinates display mod for Forge
'''
[[dependencies.coordinatesdisplay]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[37,)" #mandatory
   ordering="NONE"
   side="BOTH"
# Here's another dependency
[[dependencies.coordinatesdisplay]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17.1]"
   ordering="NONE"
   side="BOTH"
[[dependencies.coordinatesdisplay]]
   modId="cloth_config"
   mandatory=true
   versionRange="[5.3.63]"
   side="CLIENT"
