modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="coordinatesdisplay" #mandatory
version="2.1.0" #mandatory
displayName="Coordinates Display" #mandatory
logoFile="icon.png" #optional
authors="Boxadactle" #optional
description='''
A coordinates display mod for Forge
'''
[[dependencies.coordinatesdisplay]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.coordinatesdisplay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.18.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.coordinatesdisplay]]
    modId="cloth_config"
    mandatory=true
    versionRange="[6.1.48, 6.2.62]"
    side="CLIENT"
