modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Boxadactle/coordinates-display/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="coordinatesdisplay"
version="3.0.0"
displayName="Coordinates Display"
logoFile="icon.png"
authors="Boxadactle"
description='''
A Coordinates Display mod for Forge
'''
[[dependencies.coordinatesdisplay]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[46,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.coordinatesdisplay]]
    modId="minecraft"
    mandatory=true
    versionRange="1.20+"
    ordering="NONE"
    side="BOTH"
[[dependencies.coordinatesdisplay]]
    modId="cloth_config"
    mandatory=true
    versionRange="11.0.99+"
    side="CLIENT"
