modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="coordinatesdisplay" #mandatory
version="2.1.2" #mandatory
displayName="Coordinates Display" #mandatory
logoFile="icon.png" #optional
authors="Boxadactle" #optional
description='''
A Coordinates Display mod for Forge
'''
[[dependencies.coordinatesdisplay]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.coordinatesdisplay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19]"
    ordering="NONE"
    side="BOTH"
[[dependencies.coordinatesdisplay]]
    modId="cloth_config"
    mandatory=true
    versionRange="[7.0.65, 8.0.75]"
    side="CLIENT"
